services:
  postgres-db:
    image: postgres:15-alpine
    container_name: budget-postgres
    environment:
      POSTGRES_USER: userlnx
      POSTGRES_PASSWORD: super_senha_123
      POSTGRES_DB: budget_ai_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  localstack:
      image: localstack/localstack:3.0.2
      container_name: budget-sqs-local
      ports:
        - "4567:4566"
      environment:
        - SERVICES=sqs
        - AWS_DEFAULT_REGION=sa-east-1
      volumes:
        - "./volume/localstack:/var/lib/localstack"
      restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: budget-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: budget-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  pgdata: