# Configuração da porta do servidor
server.port=8080

# Chave gerada em [https://aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey)
google.ai.studio.api.key=${GOOGLE_AI_KEY}

# Ajuste de limite de tamanho de uploads para permitir arquivos de áudio
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configurações de Conexão com o PostgreSQL do Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/budget_ai_db
spring.datasource.username=userlnx
spring.datasource.password=super_senha_123
spring.datasource.driver-class-name=org.postgresql.Driver

# Inicialização automática do Schema (Cria as tabelas caso não existam)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Se quiser rodar na memória (com o Docker parado):
#spring.profiles.active=dev

# Se ligar o Docker e quiser salvar no banco real:
spring.profiles.active=prod

# 1. Região Estática (Evita que o Spring busque metadados na AWS real)
spring.cloud.aws.region.static=${AWS_REGION:sa-east-1}
spring.cloud.aws.region.use-default-providers=false

# 2. Credenciais Mockadas para o Localstack
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.credentials.use-default-providers=false

# 3. Redirecionamento do Endpoint do SQS para o Container Local
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# Configuração do Apache Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=budget-ai-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Ativação dos endpoints de Observabilidade/Métricas para Prometheus e Grafana
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true

# Faz o próprio Spring Boot ler o arquivo .env nativamente antes de subir
spring.config.import=optional:file:.env[.properties]