# Configuração da porta do servidor
server.port=8080

# Chave gerada em [https://aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey)
google.ai.studio.api.key=${GOOGLE_AI_KEY}

# Ajuste de limite de tamanho de uploads para permitir arquivos de áudio
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
